"""
Generate the CSV data for the three Section 3.1 counterexample figures.

The cases use initial points u0=2.1*1 and u0=300*1, with an additional m=3,5
comparison for u0=2.1*1. Results are written to --output-dir and can be read
by plot_counterexample.py. Table 1 is generated by run_gamma_sweep.py.
"""

import argparse
import csv
import math
import os
import sys
from time import time
from types import SimpleNamespace

import torch


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from optim_algo import AndersonAcc, GlobalAndersonSolver  # noqa: E402


DEFAULT_DIM = 200
DEFAULT_GAMMA = 1.0 / 25.0
DEFAULT_M = 1
DEFAULT_MAX_ITERS = 50
DEFAULT_FUNC_EVAL_MAX = 4 * DEFAULT_MAX_ITERS + 4
DEFAULT_TOL = 1e-8
DEFAULT_GAMMA_K_CONSTANT = 300.0
DEFAULT_LAMBDA = 1.0
DEFAULT_OUTPUT_DIR = os.path.join(SCRIPT_DIR, "results")

CASES = (
    {
        "name": "t0=2.1",
        "t0": 2.1,
        "m_values": (1,),
        "algorithms": "all",
        "output_file": "counterexample_t0_2p1.csv",
    },
    {
        "name": "t0=300",
        "t0": 300.0,
        "m_values": (1,),
        "algorithms": "all",
        "output_file": "counterexample_t0_300.csv",
    },
    {
        "name": "t0=2.1, m=3,5 residual sweep",
        "t0": 2.1,
        "m_values": (3, 5),
        "algorithms": "all",
        "output_file": "counterexample_t0_2p1_m3_m5.csv",
    },
)

ALGORITHMS = (
    ("Picard (GD)", "picard"),
    ("AA_pure", "pure"),
    ("AA_residual", "residual"),
    ("GlobalAndersonSolver", "global"),
)

CSV_FIELDS = (
    "algorithm",
    "m",
    "iter",
    "rel_res",
    "residual",
    "time",
    "step_type",
    "diagnostic_residual",
    "objective_value",
    "x_norm",
    "step_from_prev_norm",
    "s_value",
)


class HighDimNonseparableCounterexample:
    def __init__(self, dim, gamma, dtype, device):
        if dim < 2:
            raise ValueError("dim must be at least 2.")
        self.dim = int(dim)
        self.gamma = torch.as_tensor(gamma, dtype=dtype, device=device)
        self.dtype = dtype
        self.device = device

    def initial_point(self, t0, kind="constant", seed=None):
        if kind == "constant":
            return torch.full((self.dim,), float(t0), dtype=self.dtype,
                              device=self.device)
        if kind == "randn":
            generator = None
            if seed is not None:
                generator = torch.Generator(device="cpu")
                generator.manual_seed(int(seed))
            x0 = torch.randn((self.dim,), dtype=self.dtype,
                             generator=generator)
            return x0.to(self.device)
        raise ValueError(f"unknown initial point kind: {kind}")

    def phi(self, t):
        left = t * t / 20.0 - 24.9 * t - 12.45
        middle = 12.5 * t * t
        right = t * t / 20.0 + 24.9 * t - 12.45
        return torch.where(t < -1.0, left,
                           torch.where(t < 1.0, middle, right))

    def phi_prime(self, t):
        left = t / 10.0 - 24.9
        middle = 25.0 * t
        right = t / 10.0 + 24.9
        return torch.where(t < -1.0, left,
                           torch.where(t < 1.0, middle, right))

    def grad(self, x):
        s_value = x.mean()
        centered = x - s_value
        return self.phi_prime(s_value) + centered

    def map(self, x):
        return (x - self.gamma * self.grad(x)).detach()

    def residual(self, x):
        return self.map(x) - x

    def objective(self, x):
        s_value = x.mean()
        centered = x - s_value
        return self.dim * self.phi(s_value) + 0.5 * torch.dot(centered,
                                                              centered)


class IterateRecorder:
    def __init__(self):
        self.iterations = []
        self.iterates = []

    def __call__(self, iteration, x):
        self.iterations.append(int(iteration))
        self.iterates.append(x.detach().cpu().clone())

    def as_tensors(self):
        if self.iterates:
            iterates = torch.stack(self.iterates, dim=0)
        else:
            iterates = torch.empty(0)
        iterations = torch.tensor(self.iterations, dtype=torch.long)
        return iterations, iterates


def make_solver_args(cli_args):
    return SimpleNamespace(
        eta=cli_args.eta,
        lambda_=DEFAULT_LAMBDA,
        max_iters=DEFAULT_MAX_ITERS,
        func_eval_max=DEFAULT_FUNC_EVAL_MAX,
        tol=DEFAULT_TOL,
        gamma_k_constant=DEFAULT_GAMMA_K_CONSTANT,
        pure_aa_restart=False,
        residual_aa_restart=False,
        show=False,
    )


def run_picard(gd_map, x0, args, iterate_callback=None):
    x = x0.clone()
    tmk = 0.0
    orcl = 0
    iters = 0

    Sx = gd_map(x).detach()
    orcl += 1
    Fx = Sx - x
    residual_norm = Fx.norm()
    residual0_norm = torch.clamp(
        residual_norm.detach().clone(), min=torch.finfo(x.dtype).tiny)
    record = torch.tensor(
        [residual_norm / residual0_norm, residual_norm, orcl, tmk, 0, 1],
        dtype=x.dtype,
        device=x.device,
    ).reshape(1, -1)
    if iterate_callback is not None:
        iterate_callback(0, x)

    while residual_norm / residual0_norm >= args.tol \
            and iters < args.max_iters \
            and orcl < args.func_eval_max:
        t0 = time()
        x = Sx.clone()
        Sx = gd_map(x).detach()
        orcl += 1
        Fx = Sx - x
        residual_norm = Fx.norm()
        iters += 1
        tmk += time() - t0
        row = torch.tensor(
            [residual_norm / residual0_norm, residual_norm, orcl, tmk, 0, 1],
            dtype=x.dtype,
            device=x.device,
        ).reshape(1, -1)
        record = torch.cat((record, row), axis=0)
        if iterate_callback is not None:
            iterate_callback(iters, x)

    return x, record


def run_pure_aa(gd_map, x0, anderson_m, args, iterate_callback=None):
    return AndersonAcc(
        gd_map,
        x0.clone(),
        anderson_m,
        args.lambda_,
        1.0,
        args.max_iters,
        args.func_eval_max,
        0,
        0,
        0,
        0,
        0,
        gradTol=args.tol,
        show=args.show,
        arg="pure",
        restart=args.pure_aa_restart,
        regularization_eta=args.eta,
        print_final=False,
        iterate_callback=iterate_callback,
    )


def run_residual_aa(gd_map, x0, anderson_m, args, iterate_callback=None):
    return AndersonAcc(
        gd_map,
        x0.clone(),
        anderson_m,
        args.lambda_,
        1.0,
        args.max_iters,
        args.func_eval_max,
        0,
        0,
        0,
        0,
        0,
        gradTol=args.tol,
        show=args.show,
        arg="residual",
        restart=args.residual_aa_restart,
        print_final=False,
        iterate_callback=iterate_callback,
    )


def run_global_anderson_solver(gd_map, x0, anderson_m, args,
                               iterate_callback=None):
    constant = args.gamma_k_constant
    gamma_k = lambda k, x, Gk, Fk, m_k, kappa: (
        k + constant) / (k + constant + 1)

    solver = GlobalAndersonSolver(
        gd_map,
        x0.clone(),
        m=anderson_m,
        lambda_=args.lambda_,
        mainLoopMaxItrs=args.max_iters,
        funcEvalMax=args.func_eval_max,
        gamma_k=gamma_k,
        residualTol=args.tol,
        eta=args.eta,
        show=args.show,
        print_final=False,
        iterate_callback=iterate_callback,
    )
    return solver.run()


def compute_diagnostics(problem, iterations, iterates):
    if iterates.numel() == 0:
        raise ValueError("No iterates were recorded.")

    cpu_iterates = iterates.detach().cpu()
    device_iterates = cpu_iterates.to(dtype=problem.dtype,
                                      device=problem.device)
    residual_norms = torch.stack([
        problem.residual(x).norm().detach().cpu() for x in device_iterates
    ])
    objective_values = torch.stack([
        problem.objective(x).detach().cpu() for x in device_iterates
    ])
    x_norms = device_iterates.norm(dim=1).detach().cpu()
    s_values = device_iterates.mean(dim=1).detach().cpu()
    if device_iterates.shape[0] > 1:
        step_norms = (
            device_iterates[1:] - device_iterates[:-1]).norm(dim=1).detach().cpu()
    else:
        step_norms = torch.empty(0, dtype=x_norms.dtype)

    return {
        "iterations": iterations.detach().cpu(),
        "residual_norms": residual_norms,
        "objective_values": objective_values,
        "x_norms": x_norms,
        "step_norms": step_norms,
        "s_values": s_values,
    }


def step_type_from_record(algorithm, record, row_index):
    if row_index == 0:
        return "initial"
    direction_value = int(round(record[row_index, -1].item()))
    if direction_value == 0:
        return "AA"
    if algorithm == "GlobalAndersonSolver":
        return "KM"
    return "Picard"


def aa_step_percentage(algorithm, record):
    if algorithm == "Picard (GD)":
        return None
    total_steps = max(int(record.shape[0]) - 1, 0)
    if total_steps == 0:
        return 0.0
    aa_steps = sum(
        1 for row_index in range(1, int(record.shape[0]))
        if step_type_from_record(algorithm, record, row_index) == "AA"
    )
    return 100.0 * aa_steps / total_steps


def rows_for_algorithm(algorithm, anderson_m, record, diagnostics):
    rows = []
    iterations = diagnostics["iterations"]
    step_norms = diagnostics["step_norms"]
    for row_index, row in enumerate(record.detach().cpu()):
        step_from_prev = (
            "" if row_index == 0 else f"{step_norms[row_index - 1].item():.17g}"
        )
        rows.append({
            "algorithm": algorithm,
            "m": anderson_m,
            "iter": int(iterations[row_index].item()),
            "rel_res": f"{row[0].item():.17g}",
            "residual": f"{row[1].item():.17g}",
            "time": f"{row[3].item():.17g}",
            "step_type": step_type_from_record(algorithm, record, row_index),
            "diagnostic_residual": (
                f"{diagnostics['residual_norms'][row_index].item():.17g}"),
            "objective_value": (
                f"{diagnostics['objective_values'][row_index].item():.17g}"),
            "x_norm": f"{diagnostics['x_norms'][row_index].item():.17g}",
            "step_from_prev_norm": step_from_prev,
            "s_value": f"{diagnostics['s_values'][row_index].item():.17g}",
        })
    return rows


def run_algorithm(problem, x0, anderson_m, algorithm_key, algorithm_label,
                  args):
    recorder = IterateRecorder()
    if algorithm_key == "picard":
        _, record = run_picard(problem.map, x0, args, recorder)
    elif algorithm_key == "pure":
        _, record = run_pure_aa(problem.map, x0, anderson_m, args, recorder)
    elif algorithm_key == "residual":
        _, record = run_residual_aa(
            problem.map, x0, anderson_m, args, recorder)
    elif algorithm_key == "global":
        _, record = run_global_anderson_solver(
            problem.map, x0, anderson_m, args, recorder)
    else:
        raise ValueError(f"unknown algorithm key: {algorithm_key}")

    iterations, iterates = recorder.as_tensors()
    diagnostics = compute_diagnostics(problem, iterations, iterates)
    rows = rows_for_algorithm(algorithm_label, anderson_m, record,
                              diagnostics)
    return record, diagnostics, rows


def print_summary_header():
    print("-" * 122)
    print(
        f"  {'algorithm':<40} {'iterations':>10} {'rel_res':>12} "
        f"{'residual':>12} {'AA step %':>10} {'||u||':>12} {'s(u)':>12}"
    )
    print("-" * 122)


def summary_algorithm_label(algorithm, anderson_m, show_picard_m=False):
    if algorithm == "Picard (GD)" and not show_picard_m:
        return algorithm
    return f"{algorithm}, m={anderson_m}"


def print_summary_row(algorithm, anderson_m, record, diagnostics,
                      show_picard_m=False):
    aa_pct = aa_step_percentage(algorithm, record)
    aa_pct_text = "-" if aa_pct is None else f"{aa_pct:9.2f}%"
    display_algorithm = summary_algorithm_label(
        algorithm, anderson_m, show_picard_m=show_picard_m)
    print(
        f"  {display_algorithm:<40} {record.shape[0] - 1:>10d} "
        f"{record[-1, 0].item():>12.4e} {record[-1, 1].item():>12.4e} "
        f"{aa_pct_text:>10} "
        f"{diagnostics['x_norms'][-1].item():>12.4e} "
        f"{diagnostics['s_values'][-1].item():>12.4e}"
    )


def write_csv(rows, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate CSV data for the Section 3.1 counterexample.")
    parser.add_argument("--eta", type=float, default=0.0,
                        help=("Regularization eta shared by AA_pure and "
                              "GlobalAndersonSolver. AA_residual uses the "
                              "AndersonAcc default."))
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--dtype", choices=("float64", "float32"),
                        default="float64")
    parser.add_argument("--device", default="cpu")
    return parser.parse_args()


def print_common_header(cli_args):
    orbit = 249.0 * (math.sqrt(5.0) - 2.0)
    m_values = sorted({m for case in CASES for m in case["m_values"]})
    m_text = ",".join(str(value) for value in m_values)
    print("Section 3.1 counterexample data generation")
    print(f"  dim={DEFAULT_DIM}, m values={m_text}, "
          f"gamma={DEFAULT_GAMMA:.6g}, "
          f"max_iters={DEFAULT_MAX_ITERS}, tol={DEFAULT_TOL:.1e}")
    print("  GlobalAndersonSolver "
          f"gamma_k=(k+{DEFAULT_GAMMA_K_CONSTANT:g})/"
          f"(k+{DEFAULT_GAMMA_K_CONSTANT + 1:g})")
    print(f"  expected AA-GD cycle values: {-orbit:.6g}, 249, "
          f"{orbit:.6g}, -249")
    print(f"  Global/AA_pure eta={cli_args.eta:.4e}, "
          "AA_residual eta=AndersonAcc default")


def algorithms_for_case(case):
    if case["algorithms"] == "all":
        return ALGORITHMS
    raise ValueError(f"unknown algorithm group: {case['algorithms']}")


def run_case(problem, solver_args, case, output_path):
    t0 = case["t0"]
    x0 = problem.initial_point(t0, kind="constant")
    m_text = ",".join(str(value) for value in case["m_values"])
    print(f"\nCase: u0={t0:.6g}*1, m={m_text}")
    all_rows = []
    print_summary_header()
    show_picard_m = len(case["m_values"]) > 1
    m_values = tuple(case["m_values"])
    for m_index, anderson_m in enumerate(m_values):
        for algorithm_label, algorithm_key in algorithms_for_case(case):
            record, diagnostics, rows = run_algorithm(
                problem, x0, anderson_m, algorithm_key, algorithm_label,
                solver_args)
            all_rows.extend(rows)
            print_summary_row(algorithm_label, anderson_m, record,
                              diagnostics, show_picard_m=show_picard_m)
        if len(m_values) > 1 and m_index < len(m_values) - 1:
            print("-" * 122)
    print("-" * 122)

    write_csv(all_rows, output_path)
    print(f"Saved CSV to {output_path}")


def main():
    cli_args = parse_args()
    dtype = torch.float64 if cli_args.dtype == "float64" else torch.float32
    device = torch.device(cli_args.device)
    solver_args = make_solver_args(cli_args)

    problem = HighDimNonseparableCounterexample(
        dim=DEFAULT_DIM,
        gamma=DEFAULT_GAMMA,
        dtype=dtype,
        device=device,
    )

    print_common_header(cli_args)
    for case in CASES:
        output_path = os.path.join(cli_args.output_dir, case["output_file"])
        run_case(problem, solver_args, case, output_path)


if __name__ == "__main__":
    main()
